on:
  push:
    branches-ignore:
      - 'main'
      - 'refs/tags/*'
  pull_request:
    branches: [ main ]

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go test -coverprofile coverage.out -v ./...
